---
name: PaymentEconomyS
main: blugin\api\paymentpool\PaymentEconomyS
version: 1.0.0
api: [3.0.0]
authors: ['Blugin-team', 'PresentKim']
description: '[PaymentPool] Provider for onebone EconomyS'
depend: ['EconomyAPI', 'PaymentPool']
load: STARTUP
...
